### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by mezwick** [ilastik/ilastik-napari#6]
Conda: 4.10.3
Python: 3.9.7
OS: Windows 10

Hi,
I have made a new environment and tried installing the napari ilastik plugin atop napari with the following commands.... 
```
conda create -n ilastik_napari_test
conda activate ilastik_napari_test
conda install -c conda-forge napari
conda install -c ilastik-forge napari-ilastik
```
However, this returns the following error
```
(ilastik_napari_test) C:\Users\U062951>conda install -c ilastik-forge napari-ilastik
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```

Any advice how to proceed with installation? 
Thanks!

**Comment by emilmelnikov** [comment]
Currently, this plugin requires Python 3.7 due to a dependency in the `ilastik-forge` channel. When you did `conda install -c conda-forge napari`,conda installed napari and Python 3.9 into your environment, that's why `conda install -c ilastik-forge napari-ilastik` fails (it seems that conda doesn't know how to downgrade Python).

We are working on bringing our dependencies up to date with recent Python versions, it should be fixed soon. In the meantime, don't explicitly install napari into a new environment (that is, skip `conda install -c conda-forge napari`).

**Comment by mezwick** [comment]
Thanks for feedback. I have skipped as you said, but still get an install error

Commands... 

```
conda create -n ilastik_napari_3pt7 python=3.7
conda activate ilastik_napari_3pt7
conda install -c ilastik-forge napari-ilastik
```

Error...
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```

Perhaps i need to specify an earlier napari version to install?

**Comment by jandoG** [comment]
@mezwick I have the same problem. Did you manage to get this installed? If so could you let us know how? Thanks!

**Comment by k-dominik** [comment]
Current install instructions should work:

```shell
conda create -y -c ilastik-forge -c conda-forge -n my-napari-env napari pyqt=5.51 fastfilters sparse qtpy scikit-learn
conda activate my-napari-env
pip install ilastik-napari
```
